core/src/main/kotlin/org/evomaster/core/search/algorithms/MosaAlgorithm.kt

Improving the implementation of MOSA, which is now closer to the original implementation.
Instead of using the traditional dominance comparator and the non-dominated sorting algorithm, this implementation contains a number of improvements to speed-up the search, including (i) a fast non-dominance comparator described in [J1], and (ii) using a partial non-dominated sorting which ranks only the top N individual, with N=population size (see the original implementation of MOSA)
[J1] A. Panichella, "Automated Test Case Generation as a Many-Objective Optimisation Problem with Dynamic Selection of the Targets", TSE

Fixing the implementation of MOSA

---

core/src/main/kotlin/org/evomaster/core/output/TestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/formatter/MismatchedFormatException.kt
core/src/main/kotlin/org/evomaster/core/output/formatter/OutputFormatter.kt
core/src/test/kotlin/org/evomaster/core/outputformatter/TestJSONFormatter.kt

The original code of TestCaseWriter allows formatting json string if "\n" exists.  So I only create a formatter for json string (add "\n"s) using gson as shown in OutputFormatter.kt. This class can be also extended for another formats.
In addition, we may also format outputs (i.e., getFormattedString() ) based on the type, such as BodyParam or ObjectGene. But I just take string currently to reduce changes on original code.

format body para. of generated test cases

---

core/src/main/kotlin/org/evomaster/core/database/DbAction.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/RestSampler.kt
core/src/main/kotlin/org/evomaster/core/search/gene/DateTimeGene.kt
core/src/main/kotlin/org/evomaster/core/search/gene/GeneUtils.kt
core/src/test/kotlin/org/evomaster/core/search/gene/GeneUtilsTest.kt

RestSampler was not producing DbAction with repaired SqlTimestamp genes. This was due to the lack of a call to GeneUtils.repairGenes()

bugfix in RestSampler

---

core/src/main/kotlin/org/evomaster/core/search/service/monitor/SearchProcessMonitor.kt
core/src/test/kotlin/org/evomaster/core/search/service/ProcessMonitorTest.kt

As checked, the test failure is caused by a failure of file deletion in windows. Those files are access denied in windows for some reasons. For the moment, each test is set with a different folder to save monitor data for handling the test failure.

test failure is caused by a failure of file deletion in windows.

---

client-java/controller/pom.xml
client-java/controller/src/main/java/org/evomaster/client/java/controller/contentMatchers/NumberMatcher.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/expect/AggregateExpectation.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/expect/ExpectationHandler.java
core/src/main/kotlin/org/evomaster/core/output/TestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/TestSuiteWriter.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/RestActionBuilder.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/RestCallAction.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/RestFitness.kt

Some issues persist. 
1. Messages containing timestamps and/or object references cause failures.
2. Extension of Json for ProxyPrint causes some trouble. The string describing it is (in both EvoMaster and in the Api itself "application/vnd.tsdes.news+json;charset=UTF-8;version=2", but for some reason the RestAssured header reads "application/vnd.tsdes.news+json; version=2;charset=UTF-8". The reversal of charset and version appears to cause the problems.

Basic assertions v2

---

client-java/controller-api/src/main/java/org/evomaster/client/java/controller/api/EMTestUtils.java
client-java/controller-api/src/test/java/org/evomaster/client/java/controller/api/EMTestUtilsTest.java
core/src/main/kotlin/org/evomaster/core/problem/rest/RestCallResult.kt
core/src/test/kotlin/org/evomaster/core/problem/rest/RestCallResultTest.kt

I found that:
- When a resource ID was a string, then when calling the `getResourceId` method to generate the Location Header, then it was incorrectly parsed as it escaped the char `"`. For example if the payload is:
```
{ "id": "aStringId" }
```
Then, the resource id of the response was: `"\"aStringId\""`.
That resulted into generating a wrong location header, for example: `/v0/"aStringId"`. So it failed when trying to parse it as a URI in `resolveLocation`
- When a Location Header can not be parsed into a URI, then instead of returning the expected template the invalid location was returned. This caused making requests to an invalid URL and made Evomaster to stop running.

Use template when location fails parsing

---

core/src/main/kotlin/org/evomaster/core/output/TestCaseWriter.kt

TODO handling string with backslash eg., rxHhwHeR\ in gql

generate tests even with problems

---

core/src/main/kotlin/org/evomaster/core/Main.kt
core/src/main/kotlin/org/evomaster/core/output/Clusterer.kt
core/src/main/kotlin/org/evomaster/core/output/TestSuiteSplitter.kt
e2e-tests/e2e-tests-utils/src/test/java/org/evomaster/e2etests/utils/WsTestBase.java
e2e-tests/spring-rest-openapi-v3/src/main/kotlin/com/foo/rest/examples/spring/openapi/v3/cluster/ClusterApplication.kt
e2e-tests/spring-rest-openapi-v3/src/test/kotlin/com/foo/rest/examples/spring/openapi/v3/cluster/ClusterTestController.kt
e2e-tests/spring-rest-openapi-v3/src/test/kotlin/com/foo/rest/examples/spring/openapi/v3/expectations/ExpectationsController.kt
e2e-tests/spring-rest-openapi-v3/src/test/kotlin/org/evomaster/e2etests/spring/openapi/v3/cluster/ClusterEMTest.kt

I suspect the problem is that the initial filtering (when deciding whether or not clustering can be performed) assumed (rather than checked) that the Results are HttpWsActionResults. When they are not, the DBSCANClusterer attempts to perform clustering, but fails and crashes. An extra check has been added to remedy this. 
I don't have a way of replicating the problem for the moment, but I did put into place a bit of scaffolding for a future test (once I'm able to replicate the problem). Alternatively it can be removed if it turns out to be useless. 
I've made minor modifications to the visibility of a couple of methods in Main (writeTests and checkState) to allow me to edit the default EMConfig values from the defaults given by init().

Clustering bugfix

---

core/src/main/kotlin/org/evomaster/core/output/service/HttpWsTestCaseWriter.kt

it should be `res.body.property` but `body` is missing.

fix a bug in js assertion for 'null' value

---

client-js/evomaster-client-js/src/instrumentation/babel-plugin-evomaster.ts
client-js/evomaster-client-js/tests/unit/instrumentation/babel-code-test.ts

if the expression in ternary is `await`, EM.ternary is also required to be with `await`

handle replaced ternary with await

---

core/src/main/kotlin/org/evomaster/core/problem/rest/service/BlackBoxRestFitness.kt

the bug was introduced when I put the auth within bbexp that does not affect the experiment.
As checked, the exp was started before the branch was merged, and tokens are correctly obtained in tests with bb settings.

fix a bug when adding auth for bb

---

.gitignore
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/CodeJavaGenerator.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/RPCEndpointsBuilder.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ByteParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ObjectParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/PrimitiveOrWrapperParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ShortParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/StringParam.java
client-java/controller/src/test/java/com/thrift/example/artificial/EnumWithConstructor.java
client-java/controller/src/test/java/com/thrift/example/artificial/ObjectEnum.java
client-java/controller/src/test/java/com/thrift/example/artificial/PrivateFieldInRequestDto.java
client-java/controller/src/test/java/com/thrift/example/artificial/RPCInterfaceExample.java
client-java/controller/src/test/java/com/thrift/example/artificial/RPCInterfaceExampleImpl.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/ExampleBuilderTest.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/invocation/RPCSutControllerTest.java

fix some problems in test generation for industrial case studies
- enum with override `toString`
- handle setter with short and byte

Rpc test generations

---

client-java/controller/src/main/java/org/evomaster/client/java/controller/db/DbCleaner.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/db/h2/H2VersionUtils.java

I was unable to reproduce the issue on my system (running a macOS Monterrey).
Could you please provide me more information on the fault in scout-api (i.e. stack trace of the nested exception)?
Cheers,
JP
ERROR - Unexpected SQLException while fetching H2 version
java.lang.RuntimeException: Unexpected SQLException while fetching H2 version
at org.evomaster.client.java.controller.db.DbCleaner.clearDatabase_H2(DbCleaner.java:45)
at org.evomaster.client.java.controller.db.DbCleaner.clearDatabase_H2(DbCleaner.java:31)
at org.evomaster.client.java.controller.db.DbCleaner.clearDatabase_H2(DbCleaner.java:27)
at org.evomaster.client.java.controller.db.DbCleaner.clearDatabase_H2(DbCleaner.java:23)
at em.external.se.devscout.scoutapi.ExternalEvoMasterController.resetStateOfSUT(ExternalEvoMasterControl …

fix problem with H2VERSION() in scout-api

---

core/src/test/kotlin/org/evomaster/core/database/insertion/postgres/PostgresInsertValueTest.kt
e2e-tests/spring-rest-postgres/pom.xml
e2e-tests/spring-rest-postgres/src/main/kotlin/com/foo/spring/rest/postgres/json/FooDto.kt
e2e-tests/spring-rest-postgres/src/main/kotlin/com/foo/spring/rest/postgres/json/JsonColumnApp.kt
e2e-tests/spring-rest-postgres/src/main/resources/schema/json/V1.0__createDB.sql
e2e-tests/spring-rest-postgres/src/test/kotlin/com/foo/spring/rest/postgres/json/JsonColumnController.kt
e2e-tests/spring-rest-postgres/src/test/kotlin/org/evomaster/e2etests/spring/rest/postgres/json/JsonColumnEMTest.kt

I added a test case for parsing a Json schema with Gson. I think it would be a good idea to keep this e2e test case even when the schema extraction is not being used yet

json column type schema e2e test case

---

client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/ClassAnalyzer.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/JpaAnnotationName.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/JpaConstraint.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/JpaConstraintBuilder.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/NameSpace.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/staticstate/UnitsInfoRecorder.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/ClassAnalyzerTest.java

This PR includes only refactors and no change in functionality.
- Refactor in `ClassAnalyzer` which includes:
- Moving annotation names into another file
- Modified `getAnnotationName` method to remove validation of namespace not null outside
- Created a builder for `JpaConstraint`: `JpaConstraintBuilder` to avoid having a constructor with so many parameters
- Refactor `ClassAnalyzerTest` to have a `@BeforeEach` setup

Refactor JpaConstraint 

---

core/src/main/kotlin/org/evomaster/core/Main.kt
core/src/main/kotlin/org/evomaster/core/output/TestSuiteSplitter.kt
core/src/main/kotlin/org/evomaster/core/search/Solution.kt
e2e-tests/spring-rest-openapi-v2/src/main/java/com/foo/rest/examples/spring/filecreationissuenofault/FileCreationIssueNoFaultApplication.java
e2e-tests/spring-rest-openapi-v2/src/main/java/com/foo/rest/examples/spring/filecreationissuenofault/FileCreationIssueNoFaultRest.java
e2e-tests/spring-rest-openapi-v2/src/main/java/com/foo/rest/examples/spring/filecreationissuewithfault/FileCreationIssueWithFaultApplication.java
e2e-tests/spring-rest-openapi-v2/src/main/java/com/foo/rest/examples/spring/filecreationissuewithfault/FileCreationIssueWithFaultRest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/com/foo/rest/examples/spring/filecreationissuenofault/FileCreationIssueNoFaultController.java
e2e-tests/spring-rest-openapi-v2/src/test/java/com/foo/rest/examples/spring/filecreationissuewithfault/FileCreationIssueWithFaultController.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/filecreationissue/FileCreationIssueEMTest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/filecreationissue/FileCreationIssueFaultEMTest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/filecreationissue/FileCreationIssueNoFaultEMTest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/filecreationissue/FileCreationIssueTestHelper.java

https://github.com/EMResearch/EvoMaster/issues/759
By fixing the split method inside TestSuiteSplitter.kt.
Solution is not taken as it is for the executive summary. It is taken as everything being copied except Termination condition. By default, the solution object has the termination condition NONE. In this case, I changed it to Termination.SUMMARY.

Fixing the issue: #759

---

solver/src/main/java/DbConstraintSolver.java
solver/src/main/java/DbConstraintSolverZ3InDocker.java
solver/src/main/java/Smt2Writer.java
solver/src/test/java/ConstraintSolverTest.java
solver/src/test/java/Smt2WriterTest.java

Refactor solver to use the SQL DB schema to parse the constraints instead of sending them as a parameter when invoking the solve method.
As the Check constraints are already parsed as part of the DB Schema then there is no need to parse different string formats from the "CHECK" constraint as it is unified in format.
Added support for more than one variable in check constraint
- Support for string variables in the check constraint
- Support for other numeric genes besides Int
- Support for more than one table

Refactor Solver to use db schema

---

core/src/main/kotlin/org/evomaster/core/output/service/TestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/TestSuiteWriter.kt
core/src/test/kotlin/org/evomaster/core/output/service/TestSuiteWriterTest.kt

- Python test classes now contain the class name and imports.
- Test cases are created empty with the `pass` directive. This will be removed in the next PR when python tests are able to actually perform requests and assertions
- main footer added so as to be able to directly execute tests directly calling for example `python3 EvoMaster_successes_Test.py`

Python imports and init tests

---

core/src/main/kotlin/org/evomaster/core/search/EvaluatedIndividual.kt
core/src/main/kotlin/org/evomaster/core/search/impact/impactinfocollection/GeneImpact.kt
core/src/main/kotlin/org/evomaster/core/search/impact/impactinfocollection/ImpactUtils.kt
core/src/test/kotlin/org/evomaster/core/search/impact/impactinfocollection/individual/IndividualGeneImpactTest.kt

improve log for mismatched gene impact exception
https://github.com/WebFuzzing/EvoMaster/issues/983

Geneimpact errorlog

---

core/src/main/kotlin/org/evomaster/core/output/service/ApiTestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/HttpWsTestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/TestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/TestSuiteWriter.kt
core/src/test/kotlin/org/evomaster/core/output/PythonTestCaseWriterTest.kt

- Assertion over JSON without having to compare against the raw string
- Timeout for python tests

Improve Python JSON assertions, timeout for tests

---

core/src/main/kotlin/org/evomaster/core/EMConfig.kt
core/src/main/kotlin/org/evomaster/core/problem/api/service/ApiWsStructureMutator.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/ResourceRestMutator.kt
core/src/main/kotlin/org/evomaster/core/search/service/mutator/StandardMutator.kt
core/src/main/kotlin/org/evomaster/core/sql/SqlInsertBuilder.kt

This PR should not affect functionality. The changes here enable future development on `config.generateSqlDataWithDSE`.
- Replaced check from `config.generateSqlDataWithDSE` to `config.shouldGenerateSqlData()`
- Added different behavior to handle DSE and Search in `ApiWsStructureMutator`

Change validations to check shouldGenerateSqlData instead of only search

---

core/src/main/kotlin/org/evomaster/core/output/naming/ActionTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/GraphQLActionTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/NamingHelperNumberedTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/NumberedTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/RPCActionTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/RestActionTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/TestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/TestCaseNamingStrategyFactory.kt
core/src/main/kotlin/org/evomaster/core/problem/graphql/GraphQlCallResult.kt
core/src/main/kotlin/org/evomaster/core/problem/graphql/service/GraphQLFitness.kt
core/src/main/kotlin/org/evomaster/core/problem/rpc/RPCCallAction.kt
core/src/test/kotlin/org/evomaster/core/output/naming/ActionNamingStrategyTest.kt
core/src/test/kotlin/org/evomaster/core/output/naming/GraphQLActionNamingStrategyTest.kt
core/src/test/kotlin/org/evomaster/core/output/naming/RPCActionNamingStrategyTest.kt
core/src/test/kotlin/org/evomaster/core/output/naming/RestActionNamingStrategyTest.kt

- Web test cases are named with the numbered naming strategy
- Created action based naming strategy for GraphQL and RPC
- Unit tests for both cases
- Global `nameTokens` var was concatenating test case names as new ones were created (added [testTwoDifferentIndividualsGetDifferentNames](https://github.com/WebFuzzing/EvoMaster/blob/40d4bb3539796728db3d616b3d0fe4c39a6bf5e7/core/src/test/kotlin/org/evomaster/core/output/naming/RestActionNamingStrategyTest.kt#L49) for this)
- Refactor of `GraphQLFitness`, moving `hasErrors` to `GraphQlCallResult` and adding `hasNonEmptyData` as well

GraphQL, RPC and Web test case naming

---

core/src/main/kotlin/org/evomaster/core/EMConfig.kt
core/src/main/kotlin/org/evomaster/core/output/naming/ActionTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/RestActionTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/TestCaseNamingStrategyFactory.kt
core/src/test/kotlin/org/evomaster/core/EMConfigTest.kt
core/src/test/kotlin/org/evomaster/core/output/naming/RestActionNamingStrategyTest.kt
core/src/test/kotlin/org/evomaster/core/output/naming/TestCaseDisambiguationTest.kt
docs/options.md

Adding an experimental parameter for using the names of boolean query parameters which have a `true` value in test case disambiguation.
When there's more than one eligible query param, they are joined by the `and` keyword for readability purposes

True boolean query parameters are added to rest test case names experimentation

---

core/src/main/kotlin/org/evomaster/core/search/gene/datetime/TimeGene.kt
core/src/main/kotlin/org/evomaster/core/search/gene/datetime/TimeOffsetGene.kt
core/src/main/kotlin/org/evomaster/core/search/impact/impactinfocollection/ImpactUtils.kt
core/src/main/kotlin/org/evomaster/core/search/impact/impactinfocollection/value/date/TimeGeneImpact.kt
core/src/main/kotlin/org/evomaster/core/search/impact/impactinfocollection/value/date/TimeOffsetGeneImpact.kt
core/src/test/kotlin/org/evomaster/core/search/impact/impactinfocollection/date/TimeGeneImpactTest.kt

In src/main/kotlin/org/evomaster/core/search/gene/datetime/TimeGene.kt, millisecond and ofsett are missing. That causes "java.util.NoSuchElementException: Key org.evomaster.core.search.gene.optional.OptionalGene@820b78a is missing in the map." exception while running on the SUTs.
In this PR, I fixed it, but we need to check if it is the correct way.
Stacktrace:
> * Starting to generate test cases
20:33:19.044 [main] WARN  o.e.c.s.i.i.ImpactUtils - the impact of LimitObjectGene was collected in a general manner, i.e., GeneImpact
20:33:19.205 [main] WARN  o.e.c.s.i.i.ImpactUtils - the impact of CycleObjectGene was collected in a general manner, i.e., GeneImpact EvoMaster process terminated abruptly. This is likely a bug in EvoMaster. Please copy&paste the following stacktrace, and create a …

first try to fix exception related to TimeOffset impact

---

core/src/main/kotlin/org/evomaster/core/EMConfig.kt
core/src/main/kotlin/org/evomaster/core/output/naming/ActionTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/AmbiguitySolver.kt
core/src/main/kotlin/org/evomaster/core/output/naming/GraphQLActionTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/NumberedTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/RPCActionTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/TestCaseNamingStrategyFactory.kt
core/src/main/kotlin/org/evomaster/core/output/naming/rest/PathAmbiguitySolver.kt
core/src/main/kotlin/org/evomaster/core/output/naming/rest/QueryParamsAmbiguitySolver.kt
core/src/main/kotlin/org/evomaster/core/output/naming/rest/RestActionTestCaseNamingStrategy.kt
core/src/test/kotlin/org/evomaster/core/EMConfigTest.kt
core/src/test/kotlin/org/evomaster/core/output/naming/GraphQLActionNamingStrategyTest.kt
core/src/test/kotlin/org/evomaster/core/output/naming/RPCActionNamingStrategyTest.kt
core/src/test/kotlin/org/evomaster/core/output/naming/RestActionNamingStrategyTest.kt
core/src/test/kotlin/org/evomaster/core/output/naming/RestActionTestCaseUtils.kt
core/src/test/kotlin/org/evomaster/core/output/naming/RestTestCaseNameLengthTest.kt
core/src/test/kotlin/org/evomaster/core/output/naming/TestCaseDisambiguationTest.kt
docs/options.md

- Implementing a hard limit on test case name length.
- Default value is 80 chars, though it is possible to set a different one with the `maxTestCaseNameLength` parameter
- At start, the amount of chars available will be the name length minus the length of the `test_#N_` string, taking N as the size of the test suite.
- If adding a token or set of tokens to the name makes it exceed the allowed size, then they are not added.
- All of the added name tokens go through this process of checking name size in order to have an updated value of the available amount of chars for the name

Implementing hard limit for test case name length, default 80 chars

---

core/src/main/kotlin/org/evomaster/core/output/naming/ActionTestCaseNamingStrategy.kt
core/src/test/kotlin/org/evomaster/core/output/naming/EnvironmentActionsInTestCaseNamesTest.kt

Environment actions such as SQL, Mongo and WireMock will not be added as a test case name suffix if either:
- All test cases share the same action
- In a suite of more than 10 test cases, more than half of them share the same action
Number 10 was chosen thinking of a small test suite. If 6 out of 10 test cases have the `UsingMongo` suffix, repetition is not so terrible.

Environment actions suffix are only added to test case names if less than half

---

core/src/main/kotlin/org/evomaster/core/output/naming/ActionTestCaseNamingStrategy.kt
core/src/test/kotlin/org/evomaster/core/output/naming/RestActionNamingStrategyTest.kt

Simple (and silly) fix. The amount of tests were being used to calculate the remaining available chars for a test case name. Therefore, since the default length of a test case is 80 chars, whenever the suite was big enough (eg. 90 tests), the calculation was `"test_".length + 90 + 1`, this adds to 96, which when comparing to the 80 available chars, meant that no extra information could be added to the test case name.
What we were actually looking for is `"test_".length + 2 + 1`, since the number 90 uses 2 chars in naming

Test case names use amount of digits to calculate length

---

core/src/main/kotlin/org/evomaster/core/solver/SMTConditionVisitor.kt
core/src/main/kotlin/org/evomaster/core/solver/SmtLibGenerator.kt
solver/src/main/java/org/evomaster/solver/smtlib/SMTResultParser.java
solver/src/test/java/org/evomaster/solver/smtlib/SMTResultParserTest.java

1. The types map was missing "REAL" and "VARCHAR", the type name depends on the database used.
2. Fix get table name
3. Avoid creating an OrAssertion when only 1 assertion
4. Fix parsing negative numbers
5. Fix getting alias from null tables

Add not supported types for smtlib generator

---

core/src/main/kotlin/org/evomaster/core/output/naming/rest/PathAmbiguitySolver.kt
core/src/test/kotlin/org/evomaster/core/output/naming/TestCaseDisambiguationTest.kt

When two or more tests were directed at `/` and no query parameters were involved, EM attempted to retrieve the parent path of `/`, which failed. This has now been fixed and tests added for scenarios with and without query parameters.

Fixed issue when attempting to disambiguate paths at root level

---

core/src/main/kotlin/org/evomaster/core/output/dto/DtoField.kt
core/src/main/kotlin/org/evomaster/core/output/dto/DtoWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/TestSuiteWriter.kt
core/src/test/kotlin/org/evomaster/core/output/dto/DtoWriterTest.kt
core/src/test/resources/swagger/dto-writer/childObjectComponent.yaml
core/src/test/resources/swagger/dto-writer/childObjectInline.yaml
core/src/test/resources/swagger/dto-writer/primitiveTypes.yaml
core/src/test/resources/swagger/dto-writer/simpleComponents.yaml

Adding unit tests for DTO generation. The goal is to assert only that given a schema, the expected DTOs are generated in the EM abstraction. Valid code generation of DTOs will be later tested using e2e tests.
Included tests are:
- primitive types in an inline schema
- child object in an inline schema
- simple different objects in the components section
- child object in the components section

Adding unit testing for DTO generation
