core/src/main/kotlin/org/evomaster/core/database/DbAction.kt
core/src/main/kotlin/org/evomaster/core/database/schema/ColumnDataType.kt
core/src/main/kotlin/org/evomaster/core/output/TestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/search/gene/SqlForeignKeyGene.kt
core/src/test/kotlin/org/evomaster/core/output/TestCaseWriterTest.kt
e2e-tests/spring-examples/src/main/java/com/foo/rest/examples/spring/db/javatypes/JavaTypesEntity.java

Merge branch 'master' of https://github.com/EMResearch/EvoMaster into sql

commit before merge

---

core/src/main/kotlin/org/evomaster/core/search/mutator/StandardMutator.kt

if maxTestSize = 1, it is not required to do structure mutation

condition regarding structure mutation

---

core/src/main/kotlin/org/evomaster/core/problem/rest/RestActionBuilder.kt
core/src/test/kotlin/org/evomaster/core/problem/rest/service/RestActionBuilderTest.kt

add function to remove duplicated params
add a test for it

add function to remove duplicated params

---

core/src/test/kotlin/org/evomaster/core/search/gene/MapGeneTest.kt

MapGene test. The problem has been fixed previously.

Minor test addition.

---

core/src/main/kotlin/org/evomaster/core/output/TestSuiteWriter.kt

Tiny change. The test should compile now.

Fix for import generation (to reflect the updated package structure).

---

core/src/test/kotlin/org/evomaster/core/search/service/ProcessMonitorTest.kt

move output of testing monitoring to target folder

---

core/src/main/kotlin/org/evomaster/core/problem/rest/RestActionBuilder.kt
core/src/main/kotlin/org/evomaster/core/search/gene/CycleObjectGene.kt
core/src/main/kotlin/org/evomaster/core/search/gene/ObjectGene.kt

add reference type in ObjectGene. the type may help to detect relationships among actions.

add reference type for object gene

---

core/src/main/kotlin/org/evomaster/core/search/EvaluatedIndividual.kt
core/src/main/kotlin/org/evomaster/core/search/tracer/TraceableElement.kt

enable "add an element into undo track for evaluated individual"

modify tracking

---

core/src/main/kotlin/org/evomaster/core/EMConfig.kt
core/src/main/kotlin/org/evomaster/core/output/TestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/TestSuiteOrganizer.kt
core/src/main/kotlin/org/evomaster/core/output/service/TestSuiteWriter.kt
core/src/main/kotlin/org/evomaster/core/search/EvaluatedIndividual.kt
core/src/main/kotlin/org/evomaster/core/search/tracer/TraceableElement.kt

The current proof-of-concept for custom naming and sorting. 
The sorting is currently done by applying the comparators. At some point I will introduce a more explicit sorting index.

Naming sorting

---

client-java/controller/src/main/java/org/evomaster/client/java/controller/contentMatchers/NumberMatcher.java
core/src/main/kotlin/org/evomaster/core/EMConfig.kt
core/src/main/kotlin/org/evomaster/core/output/TestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/TestSuiteOrganizer.kt
core/src/main/kotlin/org/evomaster/core/search/gene/GeneUtils.kt
core/src/main/kotlin/org/evomaster/core/search/gene/StringGene.kt
core/src/test/kotlin/org/evomaster/core/output/TestCaseWriterTest.kt
core/src/test/kotlin/org/evomaster/core/output/formatter/OutputFormatterTest.kt
core/src/test/kotlin/org/evomaster/core/search/gene/GeneUtilsEscapeTest.kt
e2e-tests/spring-examples/src/main/java/com/foo/rest/examples/spring/escapes/EscapeApplication.java
e2e-tests/spring-examples/src/main/java/com/foo/rest/examples/spring/escapes/EscapeResponseDto.java
e2e-tests/spring-examples/src/main/java/com/foo/rest/examples/spring/escapes/EscapeRest.java
e2e-tests/spring-examples/src/test/java/com/foo/rest/examples/spring/escape/EscapeController.java
e2e-tests/spring-examples/src/test/java/org/evomaster/e2etests/spring/examples/escape/EscapeEMTest.java
e2e-tests/spring-examples/src/test/java/org/evomaster/e2etests/spring/examples/escape/EscapeManualTest.java
e2e-tests/spring-examples/src/test/java/org/evomaster/e2etests/spring/examples/escape/EscapeTestBase.java
e2e-tests/spring-examples/src/test/java/org/evomaster/e2etests/spring/examples/headerlocation/HLEMTest.java

Seems to work. Changes are related to:
- handling contents of arrays (especially arrays of objects).
- which strings are escaped (some strings related to the path are not escaped, as that appeared to lead to additional test failures).

Basic assertions v3

---

client-java/instrumentation-shared/src/main/java/org/evomaster/client/java/instrumentation/shared/StringSpecialization.java
client-java/instrumentation/pom.xml
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/DateTimeParsingUtils.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/DistanceHelper.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/PatternMatchingHelper.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/RegexDistanceUtils.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/ReplacementList.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/DateClassReplacement.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/DateFormatClassReplacement.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/LocalDateClassReplacement.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/LocalDateTimeClassReplacement.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/LocalTimeClassReplacement.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/MatcherClassReplacement.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/ObjectsClassReplacement.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/PatternClassReplacement.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/StringClassReplacement.java
client-java/instrumentation/src/test/java/com/foo/somedifferentpackage/examples/methodreplacement/TestabilityExcImp.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/RegexDistanceUtilsTest.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/DateClassReplacementTest.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/LocalDateClassReplacementTest.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/LocalDateTimeClassReplacementTest.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/LocalTimeClassReplacementTest.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/example/methodreplacement/TestabilityExc.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/example/methodreplacement/TestabilityExcInstrumentedTest.java
core/src/main/kotlin/org/evomaster/core/search/gene/regex/CharacterClassEscapeRxGene.kt
core/src/main/kotlin/org/evomaster/core/search/gene/regex/DisjunctionListRxGene.kt
core/src/test/kotlin/org/evomaster/core/search/gene/regex/CharacterClassEscapeRxGeneTest.kt
docs/reused_code.md
pom.xml

Implementation of TT for Java Regular Expressions

distance to regular expression

---

core/src/main/kotlin/org/evomaster/core/output/TestSuiteOrganizer.kt

The tweak to the default naming that you asked for.

Small tweak to default naming criteria.

---

core/src/main/kotlin/org/evomaster/core/EMConfig.kt
core/src/main/kotlin/org/evomaster/core/Main.kt
core/src/main/kotlin/org/evomaster/core/search/service/Archive.kt
core/src/main/kotlin/org/evomaster/core/search/service/Statistics.kt
e2e-tests/spring-examples/src/test/java/org/evomaster/e2etests/spring/examples/impact/ImpactEMTest.java
e2e-tests/spring-examples/src/test/java/org/evomaster/e2etests/spring/examples/impact/ObjectImpactEMTest.java

regarding https://trello.com/c/DLK8Q4Nc/212-create-txt-files-with-list-of-covered-targets-at-end-of-search-sorted-alphabetically

export info of coveredtargets

---

core/src/main/kotlin/org/evomaster/core/output/TestCaseWriter.kt

This is the fix for the extra size checks that appeared in the code.

Assertion fix v2

---

docs/write_driver.md

Hi,
is this clarification good enough for #169  ?

clarification on the TCP ports

---

core/src/main/kotlin/org/evomaster/core/problem/rest/RestActionBuilderV3.kt
core/src/test/kotlin/org/evomaster/core/problem/rest/RestActionBuilderV3Test.kt

`refClass` of `ObjectGene` is missing

missing refclass of ObjectGene

---

core/src/main/kotlin/org/evomaster/core/EMConfig.kt
core/src/main/kotlin/org/evomaster/core/docs/ConfigToMarkdown.kt
docs/options.md

The Experimental Annotation Problem Solution

ExperimentalAnnotationSolved

---

report/pom.xml

refer to updated spring-example module id

report pom.xml for the updated spring-rest-example

---

core/src/main/kotlin/org/evomaster/core/problem/rest/seeding/postman/PostmanParser.kt
core/src/test/resources/postman/query_header_path.postman_collection.json
core/src/test/resources/postman/query_header_path_wrong_values.postman_collection.json

This fixes the errors related to query parameters not being URL-encoded. Postman collections MUST have their query parameters URL-encoded.

Postman seeding

---

e2e-tests/spring-rest-openapi-v2/src/main/java/com/foo/rest/examples/spring/adaptivehypermutation/service/FooRestAPI.java

change the parameter name from `info` to `z`

modify the name of parameter as described in the paper

---

docs/joss-paper/paper.md

Combines instances of multiple citations into single commands

Fixes citations in paper.md

---

core/src/main/kotlin/org/evomaster/core/output/PartialOracles.kt

Quick fix - deactivated the SchemaOracle while it's being worked on.

---

core/src/main/kotlin/org/evomaster/core/search/service/Statistics.kt

Minor adjustment. 500 faults and expectations failures are counted separately and mutually exclusive.

Adjustment to counting expectation failures.

---

client-js/evomaster-client-js/src/controller/api/dto/AuthenticationDto.ts
client-js/evomaster-client-js/src/controller/api/dto/CookieLoginDto.ts
client-js/evomaster-client-js/src/index.ts

export headerdto

---

client-js/evomaster-client-js/src/instrumentation/InjectedFunctions.ts
client-js/evomaster-client-js/src/instrumentation/babel-plugin-evomaster.ts
client-js/evomaster-client-js/src/instrumentation/heuristic/HeuristicsForBooleans.ts
client-js/evomaster-client-js/src/instrumentation/staticstate/ExecutionTracer.ts
client-js/evomaster-client-js/tests/unit/instrumentation/babel-code-test.ts
client-js/integration-tests/tests/snippets/babel-eval-test.js

Js handle ternary

---

core/src/main/kotlin/org/evomaster/core/output/TestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/problem/graphql/GraphQlCallResult.kt
core/src/main/kotlin/org/evomaster/core/problem/graphql/service/GraphQLFitness.kt
core/src/main/kotlin/org/evomaster/core/problem/httpws/service/HttpWsFtiness.kt
core/src/main/kotlin/org/evomaster/core/search/FitnessValue.kt
core/src/main/kotlin/org/evomaster/core/search/service/IdMapper.kt
core/src/main/kotlin/org/evomaster/core/search/service/Statistics.kt
e2e-tests/e2e-tests-utils/src/test/java/org/evomaster/e2etests/utils/GraphQLTestBase.java
e2e-tests/spring-graphql/src/main/kotlin/com/foo/graphql/errors/ErrorsApplication.kt
e2e-tests/spring-graphql/src/main/kotlin/com/foo/graphql/errors/QueryResolver.kt
e2e-tests/spring-graphql/src/main/resources/errors.graphqls
e2e-tests/spring-graphql/src/test/kotlin/com/foo/graphql/errors/ErrorsController.kt
e2e-tests/spring-graphql/src/test/kotlin/org/evomaster/e2etests/spring/graphql/db/base/DbBaseEMTest.kt
e2e-tests/spring-graphql/src/test/kotlin/org/evomaster/e2etests/spring/graphql/errors/ErrorsEMTest.kt

handle error targets with tests

Gql error targets

---

core/src/main/kotlin/org/evomaster/core/output/TestCaseWriter.kt

handle array and object in array
handle null

handling assertion with response

---

core/src/main/kotlin/org/evomaster/core/output/oracles/ImplementedOracle.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/RestActionBuilderV3.kt

There should be no multiple paths at all anymore. However, I've left the code handling multiple paths (to make the thing more resilient and prevent any crashes).

Adjusted the path lookup. 

---

core/src/main/kotlin/org/evomaster/core/problem/rest/RestActionBuilderV3.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/AbstractRestFitness.kt
core/src/test/kotlin/org/evomaster/core/problem/rest/RestActionBuilderV3Test.kt
core/src/test/resources/swagger/artificial/reference_type_v2.json
core/src/test/resources/swagger/artificial/reference_type_v3.json

fix missing referType in ObjectGene
add tests for openAPI v2 and v3

referType in RestActionBuilderV3.kt

---

e2e-tests/spring-rest-openapi-v2/src/main/java/com/foo/rest/examples/spring/hypermutation/HighWeightApplication.java
e2e-tests/spring-rest-openapi-v2/src/main/java/com/foo/rest/examples/spring/hypermutation/HighWeightDto.java
e2e-tests/spring-rest-openapi-v2/src/main/java/com/foo/rest/examples/spring/hypermutation/HighWeightRest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/com/foo/rest/examples/spring/hypermutation/HighWeightRestController.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/adaptivehypermutation/AHypermutationAWHTest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/hypermutation/AdaptiveHypermutationTest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/hypermutation/HypermutationTest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/hypermutation/HypermutationTestBase.java

disable the adaptive hypermutation example 
add new simple e2e tests for it

adaptive hypermutation e2e test

---

core-it/src/test/kotlin/org/evomaster/core/problem/rest/service/resource/ResourceTestBase.kt

fix a bug that uses the mismatched inputs

---

core/src/main/kotlin/org/evomaster/core/database/DbActionResult.kt
core/src/main/kotlin/org/evomaster/core/output/service/WebTestCaseWriter.kt

fix the issue of DbActionResult

add missing copy() in DbActionResult.kt

---

client-js/evomaster-client-js/src/instrumentation/babel-plugin-evomaster.ts
client-js/evomaster-client-js/src/instrumentation/staticstate/ExecutionTracer.ts
client-js/evomaster-client-js/tests/unit/instrumentation/babel-code-test.ts
client-js/integration-tests/tests/snippets/babel-eval-test.js
core/src/main/kotlin/org/evomaster/core/output/service/HttpWsTestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/problem/graphql/service/GraphQLFitness.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/BlackBoxRestFitness.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/RestFitness.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/RestResourceFitness.kt
core/src/main/kotlin/org/evomaster/core/search/EvaluatedIndividual.kt
core/src/test/kotlin/org/evomaster/core/output/EvaluatedIndividualBuilder.kt
core/src/test/kotlin/org/evomaster/core/output/TestCaseWriterTest.kt

the problem is identified by js case study which has the timeout action.
**Note that the branch is from the pure analysis.**
**Please handle it after pure analysis.**
In addition, fix a problem in js test writer and add a test

Handle stopping action results 

---

core/src/main/kotlin/org/evomaster/core/output/service/HttpWsTestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/search/StructuralElement.kt
core/src/test/kotlin/org/evomaster/core/output/TestCaseWriterTest.kt

fix a bug in tests writer for js and add a test for it.
modify a log info

fix a bug in tests writer for js

---

e2e-tests/spring-rest-mysql/pom.xml
e2e-tests/spring-rest-mysql/src/main/kotlin/com/foo/spring/rest/mysql/mybatis/MyFooApp.kt
e2e-tests/spring-rest-mysql/src/main/kotlin/com/foo/spring/rest/mysql/mybatis/entity/Foo.kt
e2e-tests/spring-rest-mysql/src/main/kotlin/com/foo/spring/rest/mysql/mybatis/mapper/FooMapper.kt
e2e-tests/spring-rest-mysql/src/main/kotlin/com/foo/spring/rest/mysql/mybatis/service/FooRestAPI.kt
e2e-tests/spring-rest-mysql/src/main/resources/schema/myfoo/V1.0__createDB.sql
e2e-tests/spring-rest-mysql/src/test/kotlin/com/foo/spring/rest/mysql/mybatis/MyFooController.kt
e2e-tests/spring-rest-mysql/src/test/kotlin/org/evomaster/e2etests/spring/rest/mybatis/MyFooEMTest.kt
pom.xml

add an e2e test for mysql with myabtis

add e2e test for mysql with mybatis

---

client-js/e2e-tests/e2e.sh
client-js/evomaster-client-js/src/controller/api/dto/AuthenticationDto.ts
client-js/evomaster-client-js/src/controller/api/dto/JsonTokenPostLoginDto.ts
client-js/evomaster-client-js/src/index.ts
client-js/integration-tests/src/login-token/Auth.js
client-js/integration-tests/src/login-token/app.js
client-js/integration-tests/tests/login-token/app-driver.js
client-js/integration-tests/tests/login-token/args.txt
client-js/integration-tests/tests/login-token/em-main.js
core/src/main/kotlin/org/evomaster/core/output/TokenWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/HttpWsTestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/WebTestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/problem/httpws/service/auth/AuthenticationInfo.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/AbstractRestFitness.kt

- enable loginjson auth for js
- e2e test

Js auth token

---

core/src/main/kotlin/org/evomaster/core/database/SqlInsertBuilder.kt
e2e-tests/spring-rest-mysql/src/main/kotlin/com/foo/spring/rest/mysql/exisitingdata/ExistingDataApp.kt
e2e-tests/spring-rest-mysql/src/main/resources/schema/existingdata/V1.0__createDB.sql
e2e-tests/spring-rest-mysql/src/test/kotlin/com/foo/spring/rest/mysql/exisitingdata/ExistingDataController.kt
e2e-tests/spring-rest-mysql/src/test/kotlin/org/evomaster/e2etests/spring/rest/exisitingdata/ExistingDataEMTest.kt

-fix a problem in creating select sql for mysql
-add e2e test

fix a problem in handling existing data with mysql

---

client-java/controller-api/src/main/java/org/evomaster/client/java/controller/api/dto/database/schema/ColumnDto.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/internal/db/SchemaExtractor.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/internal/db/mysql/MySQLSchemaExtractorTest.java
core/src/main/kotlin/org/evomaster/core/database/DbActionGeneBuilder.kt
core/src/main/kotlin/org/evomaster/core/database/schema/Column.kt
core/src/main/kotlin/org/evomaster/core/database/schema/ColumnDataType.kt
core/src/main/kotlin/org/evomaster/core/database/schema/ColumnFactory.kt
core/src/main/kotlin/org/evomaster/core/search/gene/IntegerGene.kt
core/src/main/kotlin/org/evomaster/core/search/gene/LongGene.kt
core/src/main/kotlin/org/evomaster/core/search/service/Randomness.kt
core/src/main/kotlin/org/evomaster/core/search/service/mutator/genemutation/ArchiveGeneMutator.kt
e2e-tests/spring-rest-mysql/src/main/resources/schema/basic/V1.0__createDB.sql
e2e-tests/spring-rest-mysql/src/test/kotlin/org/evomaster/e2etests/spring/rest/basic/BasicEMTest.kt

- extract unsigned attribute for mysql numeric datatype
- extend LongGene with min and max
- modify db gene builder regarding unsigned types
- tests for updated schema extractor and Gene builder

handle unsigned datatype

---

client-js/evomaster-client-js/src/instrumentation/babel-plugin-evomaster.ts
client-js/evomaster-client-js/tests/unit/instrumentation/babel-code-test.ts

fix a bug in pure analysis in order to handle logicExp in a logicExp

fix a bug in js pure analysis

---

client-js/evomaster-client-js/src/instrumentation/babel-plugin-evomaster.ts
client-js/evomaster-client-js/tests/unit/instrumentation/babel-code-test.ts
client-js/integration-tests/tests/snippets/babel-eval-test.js

handle async property of replaced arrow function for logic expression and ternary.

handle async when using arrow function

---

core/src/main/kotlin/org/evomaster/core/search/gene/GeneUtils.kt
core/src/test/kotlin/org/evomaster/core/output/TestCaseWriterTest.kt

bug in applyAssertionEscapes if the value is email

add a test to reproduce the bug

---

core/src/main/kotlin/org/evomaster/core/problem/rest/service/BlackBoxRestFitness.kt

add missing auth handling in bb
is it only applicable when `bbExperiments` is enabled?

handle auth in bb

---

core/src/main/kotlin/org/evomaster/core/problem/graphql/service/GraphQLBlackBoxModule.kt
core/src/main/kotlin/org/evomaster/core/search/FitnessValue.kt
e2e-tests/spring-graphql/src/main/kotlin/com/foo/graphql/onlyerrors/OnlyErrorsApplication.kt
e2e-tests/spring-graphql/src/main/kotlin/com/foo/graphql/onlyerrors/QueryResolver.kt
e2e-tests/spring-graphql/src/main/resources/onlyerrors.graphqls
e2e-tests/spring-graphql/src/test/kotlin/com/foo/graphql/onlyerrors/OnlyErrorsController.kt
e2e-tests/spring-graphql/src/test/kotlin/org/evomaster/e2etests/spring/graphql/errors/ErrorsInStatisticsUtil.kt
e2e-tests/spring-graphql/src/test/kotlin/org/evomaster/e2etests/spring/graphql/errors/OnlyErrorsEMTest.kt

fix gql error related statistic bugs

---

client-java/controller/src/test/java/org/evomaster/client/java/controller/internal/db/SqlHandlerInDBTest.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/internal/db/h2/H2CheckPreparedStatementTest.java
client-java/instrumentation/pom.xml
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/PreparedStatementClassReplacement.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/StatementClassReplacement.java
core/src/main/kotlin/org/evomaster/core/problem/rest/service/RestFitness.kt

update interpolateSqlString with JSqlParser
remove comments
as investigated, no need to handle prepared statements of zebra

Sql handling

---

e2e-tests/spring-rest-openapi-v2/src/main/java/com/foo/rest/examples/spring/hypermutation/HighWeightRest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/hypermutation/AdaptiveHypermutationTest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/hypermutation/HypermutationTest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/hypermutation/HypermutationTestBase.java

fix bugs in hm e2e test

---

core/src/main/kotlin/org/evomaster/core/problem/rest/service/AbstractRestSampler.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/ResourceDepManageService.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/ResourceSampler.kt
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/resource/seedtest/RestResourceSamplerSeedTestTest.java

fix a bug of handling seeded tests

fix a bug of creating seeded tests in resource setting

---

core/src/main/kotlin/org/evomaster/core/EMConfig.kt
docs/options.md

enable skipping failed sql as default setting

remove exp tage for skipping failed sql

---

client-dotnet/src/EvoMaster.Controller.Tests/Controllers/db/DbCleanTestBase.cs
client-dotnet/src/EvoMaster.Controller.Tests/Controllers/db/DbCleanerMSSqlServerTest.cs
client-dotnet/src/EvoMaster.Controller.Tests/Controllers/db/DbCleanerMySqlTest.cs
client-dotnet/src/EvoMaster.Controller.Tests/Controllers/db/DbCleanerPostgresTest.cs
client-dotnet/src/EvoMaster.Controller.Tests/Controllers/db/DbCleanerWithSchemaMSSqlServerTest.cs
client-dotnet/src/EvoMaster.Controller/Controllers/db/DbCleaner.cs
client-dotnet/src/EvoMaster.Controller/Controllers/db/SqlScriptRunner.cs
client-dotnet/src/EvoMaster.DatabaseController/Containers/SqlServerContainer.cs
client-dotnet/src/EvoMaster.DatabaseController/SqlServerDatabaseStarter.cs
client-java/controller/src/main/java/org/evomaster/client/java/controller/db/DbCleaner.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/db/DbCleanerSQLServerWithSchemaTest.java

enable configuring with image version
dbclean for table with schema in ms SQL server for dotnet and java
updates tests for cleaning tables with specific schema

Dotnet sut fix

---

core/src/main/kotlin/org/evomaster/core/output/oracles/ImplementedOracle.kt
e2e-tests/spring-rest-openapi-v3/src/main/kotlin/com/foo/rest/examples/spring/openapi/v3/expectations/ExpectationBasicApplication.kt
e2e-tests/spring-rest-openapi-v3/src/main/kotlin/com/foo/rest/examples/spring/openapi/v3/expectations/ExpectationBasicRest.kt
e2e-tests/spring-rest-openapi-v3/src/main/kotlin/com/foo/rest/examples/spring/openapi/v3/expectations/ExpectationNumApplication.kt
e2e-tests/spring-rest-openapi-v3/src/main/kotlin/com/foo/rest/examples/spring/openapi/v3/expectations/ExpectationRest.kt
e2e-tests/spring-rest-openapi-v3/src/main/kotlin/com/foo/rest/examples/spring/openapi/v3/expectations/ExpectationsNumRest.kt
e2e-tests/spring-rest-openapi-v3/src/main/resources/static/openapi-basic-exp-test-bkp.json
e2e-tests/spring-rest-openapi-v3/src/main/resources/static/openapi-basic-exp-test.json
e2e-tests/spring-rest-openapi-v3/src/main/resources/static/openapi-expectation-test.json
e2e-tests/spring-rest-openapi-v3/src/main/resources/static/openapi-num-test.json
e2e-tests/spring-rest-openapi-v3/src/main/resources/static/swagger-expectation-test.json
e2e-tests/spring-rest-openapi-v3/src/main/resources/static/swagger-num-test.json
e2e-tests/spring-rest-openapi-v3/src/test/kotlin/com/foo/rest/examples/spring/openapi/v3/expectations/ExpectationBasicTestController.kt
e2e-tests/spring-rest-openapi-v3/src/test/kotlin/com/foo/rest/examples/spring/openapi/v3/expectations/ExpectationNumTestController.kt
e2e-tests/spring-rest-openapi-v3/src/test/kotlin/com/foo/rest/examples/spring/openapi/v3/expectations/ExpectationsTestController.kt
e2e-tests/spring-rest-openapi-v3/src/test/kotlin/org/evomaster/e2etests/spring/openapi/v3/expectations/ExpectationBasicEMTest.kt
e2e-tests/spring-rest-openapi-v3/src/test/kotlin/org/evomaster/e2etests/spring/openapi/v3/expectations/ExpectationNumEMTest.kt

Fixed the base path thing. I have added some more tests, some with OpenAPI v2 and some with v3 (and a bit of a chance to select between them).

Base path fix

---

client-java/controller/src/test/java/com/thrift/example/artificial/RPCInterfaceExample.java
client-java/controller/src/test/java/com/thrift/example/artificial/RPCInterfaceExampleImpl.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/ExampleBuilderTest.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/invocation/FakeSutController.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/invocation/RPCSutControllerTest.java
core/src/main/kotlin/org/evomaster/core/problem/rpc/service/RPCEndpointsHandler.kt

fix a problem for handling local auth in test generations
add test

Rpc localauth generation

---

client-java/controller/src/main/java/org/evomaster/client/java/controller/SutHandler.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/db/SqlScriptRunner.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/internal/SutController.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/internal/db/InitSqlScriptWithSmartDbCleanTest.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/internal/db/h2/DatabaseFakeH2SutController.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/internal/db/h2/H2InitSqlScriptWithSmartDbCleanTest.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/internal/db/mysql/DatabaseFakeMySQLSutController.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/internal/db/mysql/MySQLInitSqlScriptWithSmartDbCleanTest.java
core/src/main/kotlin/org/evomaster/core/database/SqlInsertBuilder.kt
core/src/main/kotlin/org/evomaster/core/output/service/RPCTestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/TestSuiteWriter.kt
core/src/main/kotlin/org/evomaster/core/problem/api/service/ApiWsIndividual.kt
core/src/main/kotlin/org/evomaster/core/problem/api/service/ApiWsSampler.kt
core/src/main/kotlin/org/evomaster/core/search/service/Sampler.kt
core/src/test/kotlin/org/evomaster/core/search/algorithms/constant/ConstantModule.kt
core/src/test/kotlin/org/evomaster/core/search/algorithms/onemax/ManipulatedOneMaxModule.kt
core/src/test/kotlin/org/evomaster/core/search/algorithms/onemax/OneMaxModule.kt
core/src/test/kotlin/org/evomaster/core/search/matchproblem/PrimitiveTypeMatchModule.kt
e2e-tests/e2e-tests-utils/src/test/java/org/evomaster/e2etests/utils/WsTestBase.java
e2e-tests/spring-graphql/src/test/kotlin/org/evomaster/e2etests/spring/graphql/db/directint/DbDirectIntEMTest.kt
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/adaptivehypermutation/EvoMasterAWHSampleTest.kt
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/adaptivehypermutation/ManualRestTest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/db/directint/DbDirectIntEMTest.java
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/org/evomaster/e2etests/spring/rpc/examples/db/directint/DbDirectIntEMTest.java

fix a problem on missing init data if the accessed table is empty
`resetDatabase` with specific tables

Fix smart dbreset

---

core/src/main/kotlin/org/evomaster/core/problem/rest/RestActionBuilderV3.kt
core/src/test/kotlin/org/evomaster/core/problem/rest/RestActionBuilderV3Test.kt
core/src/test/resources/swagger/artificial/positive_integer_swagger_errors.json

skip endpoints in schema if there eixst errors, eg, incorrect type instead of exception thrown.

Skip endpoints haserror

---

core/src/main/kotlin/org/evomaster/core/problem/rest/service/ResourceManageService.kt
core/src/main/kotlin/org/evomaster/core/search/impact/impactinfocollection/ImpactUtils.kt

the update was checked with EMB

fix a bug which leads to ocvn crash

---

client-java/controller/src/main/java/org/evomaster/client/java/controller/internal/EMController.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/internal/SutController.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/RPCEndpointsBuilder.java
core/src/main/kotlin/org/evomaster/core/Main.kt

fix a problem for identifying setter
provide msg of extraction error to core

Log error rpcextraction

---

client-js/evomaster-client-js/src/instrumentation/methodreplacement/SquareBracketsHandler.ts
client-js/evomaster-client-js/tests/unit/instrumentation/babel-code-test.ts
client-js/integration-tests/tests/snippets/babel-eval-test.js

fix the problem in trello for disease-api sut

fix member exp such as string.length

---

core/src/main/kotlin/org/evomaster/core/parser/RegexHandler.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/resource/RestResourceNode.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/resource/dependency/CreationChain.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/seeding/postman/PostmanParser.kt
core/src/main/kotlin/org/evomaster/core/search/Individual.kt
core/src/main/kotlin/org/evomaster/core/search/StructuralElement.kt
core/src/main/kotlin/org/evomaster/core/search/gene/ArrayGene.kt
core/src/main/kotlin/org/evomaster/core/search/gene/MapGene.kt
core/src/test/kotlin/org/evomaster/core/search/structuralelement/StructuralElementBaseTest.kt
core/src/test/kotlin/org/evomaster/core/search/structuralelement/gene/BasicGeneStructureTest.kt
core/src/test/kotlin/org/evomaster/core/search/structuralelement/gene/RegexGeneStructureTest.kt
core/src/test/kotlin/org/evomaster/core/search/structuralelement/individual/RestIndividualStructureTest.kt
core/src/test/kotlin/org/evomaster/core/search/structuralelement/simple/BasicElementCopyTest.kt

fix the incorrect log in `StructuralElement.copy()`

handle parent check

---

client-js/evomaster-client-js/tests/unit/instrumentation/babel-code-test.ts
client-js/integration-tests/tests/snippets/babel-eval-test.js

add tests to check Array with square brackets and dot notations

add tests for checking square brackets for array and its length

---

core-it/src/test/kotlin/org/evomaster/core/problem/rest/service/resource/model/SimpleResourceSampler.kt
core/src/main/kotlin/org/evomaster/core/output/service/WebTestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/resource/ExcludedResourceNode.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/resource/RestResourceNode.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/AbstractRestSampler.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/ResourceManageService.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/ResourceSampler.kt
e2e-tests/spring-rest-mysql/src/test/kotlin/org/evomaster/e2etests/spring/rest/basic/BasicEMTest.kt
e2e-tests/spring-rest-openapi-v2/src/main/java/com/foo/rest/examples/spring/SwaggerConfiguration.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/hypermutation/HypermutationTestBase.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/impactXYZ/ArchiveGeneSelectionImpactXYZInfoTest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/resource/seedtest/RestResourceSamplerSeedTestTest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/testability/MutatorWithTestabilityRestTest.java
e2e-tests/spring-rest-openapi-v3/src/test/kotlin/org/evomaster/e2etests/spring/openapi/v3/boottimetargets/BootTimeTargetsEMTest.kt

define exclude actions which are needed to be executed but not part of action clusters

Exclude action

---

client-java/controller/src/main/java/org/evomaster/client/java/controller/internal/SutController.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ArrayParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/BigDecimalParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/BigIntegerParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ByteBufferParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ListParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/MapParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/NamedTypedValue.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ObjectParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/PairParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/PrimitiveOrWrapperParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/SetParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/StringParam.java
client-java/controller/src/test/java/com/thrift/example/artificial/RPCInterfaceExample.java
client-java/controller/src/test/java/com/thrift/example/artificial/RPCInterfaceExampleImpl.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/ExampleBuilderTest.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/invocation/FakeSutController.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/invocation/RPCSutControllerTest.java

handle some problem in deserializing seeded test dto with generic types

Seedtest deserialization

---

client-java/controller-api/src/main/java/org/evomaster/client/java/controller/api/dto/problem/rpc/RPCActionDto.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/internal/SutController.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/EndpointSchema.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/LocalAuthSetupSchema.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ArrayParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/BigDecimalParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/BigIntegerParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ByteBufferParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ListParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/MapParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/NamedTypedValue.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ObjectParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/PairParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/PrimitiveOrWrapperParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/SetParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/StringParam.java
client-java/controller/src/test/java/com/thrift/example/artificial/RPCInterfaceExample.java
client-java/controller/src/test/java/com/thrift/example/artificial/RPCInterfaceExampleImpl.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/ExampleBuilderTest.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/invocation/FakeSutController.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/invocation/RPCSutControllerTest.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/thrift/ThriftTestEndpointsBuilderTest.java
core/src/main/kotlin/org/evomaster/core/output/service/RPCTestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/TestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/TestSuiteWriter.kt
core/src/main/kotlin/org/evomaster/core/problem/rpc/service/RPCEndpointsHandler.kt

use client variable for rpc function execution in the generated tests

Client variable

---

core/src/main/kotlin/org/evomaster/core/problem/rest/RestActionBuilderV3.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/AbstractRestSampler.kt
core/src/test/kotlin/org/evomaster/core/problem/rest/RestPathTest.kt
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/blackbox/BlackBoxConstantEMTest.java

handle url for call swagger for bb

Bb url call swagger

---

core/src/main/kotlin/org/evomaster/core/problem/rest/service/ResourceDepManageService.kt

skip updating param info for excluded resource node

skip resource handling for excluded resource node

---

client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ArrayParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ListParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ObjectParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/SetParam.java
client-java/instrumentation/pom.xml
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/methodreplacement/classes/MapClassReplacement.java
client-java/instrumentation/src/test/java/com/foo/somedifferentpackage/examples/methodreplacement/subclass/SubclassExmImp.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/example/methodreplacement/subclass/SubclassExm.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/example/methodreplacement/subclass/SubclassExmInstrumentedTest.java
core/src/main/kotlin/org/evomaster/core/problem/rpc/service/RPCEndpointsHandler.kt
core/src/main/kotlin/org/evomaster/core/search/gene/BigDecimalGene.kt
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/com/foo/rpc/examples/spring/numericstring/NumericStringWithSeedTestController.java
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/org/evomaster/e2etests/spring/rpc/examples/numericstring/NumericStringWithSeedEMTest.java

fix some problems in handling seeded tests dto
add an e2e test

Fix seeded tests

---

client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/RPCEndpointsBuilder.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/RPCExceptionHandler.java
client-java/controller/src/test/java/com/thrift/example/artificial/RPCInterfaceExample.java
client-java/controller/src/test/java/com/thrift/example/artificial/RPCInterfaceExampleImpl.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/ExampleBuilderTest.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/RPCEndpointsBuilderTestBase.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/invocation/RPCSutControllerTest.java
core/src/test/kotlin/org/evomaster/core/search/mutationweight/MutationWeightControlTest.kt
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/com/foo/rpc/examples/spring/authsetup/AuthLocalSetupController.java
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/com/foo/rpc/examples/spring/authsetup/AuthSetupController.java
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/com/foo/rpc/examples/spring/db/directint/DbDirectIntController.java
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/com/foo/rpc/examples/spring/hypermutation/HypermutationController.java
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/com/foo/rpc/examples/spring/regexdate/RegexDateController.java
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/com/foo/rpc/examples/spring/thriftexception/ThriftExceptionRPCController.java

handle type general with considerations of other handled RPC types (eg Thrift).

Rpc general

---

core/src/main/kotlin/org/evomaster/core/problem/api/service/ApiWsIndividual.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/RestIndividual.kt
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/adaptivehypermutation/AHypermutationAWHTest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/hypermutation/HypermutationTest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/resource/hypermutation/ResourceDbMIOAndHypermutationBasicTest.java

this PR is for fixing
AHypermutationAWHTest
testRunMIO()
testRunMIOAWH()
HypermutationTest
testRunHypermutation()
ResourceDependencyDBEMTest
testRunEM()
ResourceDependencyEMTest
testRunEM()
ResourceDbMIOAndHypermutationBasicTest
testResourceHypermutation()

Fix hw res tests

---

core-it/src/test/kotlin/org/evomaster/core/problem/rest/service/resource/ResourceTestBase.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/ResourceManageService.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/ResourceSampleMethodController.kt
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/resource/nodb/ResourceDependencyDisableDBEMTest.java

refer to `"--generateSqlDataWithSearch false"` not working

Fix enable sql data generation

---

client-java/controller-api/src/main/java/org/evomaster/client/java/controller/api/ControllerConstants.java
client-java/controller-api/src/main/java/org/evomaster/client/java/controller/api/dto/PostSearchActionDto.java
client-java/controller-api/src/main/java/org/evomaster/client/java/controller/api/dto/RPCTestDto.java
client-java/controller-api/src/main/java/org/evomaster/client/java/controller/api/dto/problem/rpc/EvaluatedRPCActionDto.java
client-java/controller-api/src/main/java/org/evomaster/client/java/controller/api/dto/problem/rpc/MockRPCExternalServiceDto.java
client-java/controller-api/src/main/java/org/evomaster/client/java/controller/api/dto/problem/rpc/SeededRPCTestDto.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/CustomizationHandler.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/internal/EMController.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/internal/SutController.java
core-it/src/test/kotlin/org/evomaster/core/problem/rest/SamplerVerifierTest.kt
core/src/main/kotlin/org/evomaster/core/EMConfig.kt
core/src/main/kotlin/org/evomaster/core/output/service/RPCTestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/TestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/TestSuiteWriter.kt
core/src/main/kotlin/org/evomaster/core/problem/rpc/service/RPCEndpointsHandler.kt
core/src/main/kotlin/org/evomaster/core/remote/service/RemoteController.kt
core/src/main/kotlin/org/evomaster/core/remote/service/RemoteControllerImplementation.kt
core/src/test/kotlin/org/evomaster/core/problem/rest/individual/RestIndividualTestBase.kt
docs/options.md
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/com/foo/rpc/examples/spring/numericstring/NumericStringWithSeedTestController.java
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/org/evomaster/e2etests/spring/rpc/examples/numericstring/NumericStringWithSeedEMTest.java

extend rpc for supporting customization of RPC test outputs

Rpc seed extend

---

core/src/test/kotlin/org/evomaster/core/search/gene/GeneTest.kt

the disabled test seems pass now.

pass on local then check on CI

---

client-java/controller-api/src/main/java/org/evomaster/client/java/controller/api/dto/problem/rpc/RPCActionDto.java

Rpc dto fix

---

core/src/main/kotlin/org/evomaster/core/problem/graphql/GraphQLIndividual.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/resource/RestResourceNode.kt
core/src/main/kotlin/org/evomaster/core/search/service/mutator/StandardMutator.kt
e2e-tests/e2e-tests-utils/src/test/java/org/evomaster/e2etests/utils/GraphQLTestBase.java
e2e-tests/spring-rest-h2-v1/src/test/java/org/evomaster/e2etests/spring/examples/db/directintwithsql/DbDirectIntWithSqlEMTest.java
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/org/evomaster/e2etests/spring/rpc/examples/branches/BranchesRPCEMTest.java
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/org/evomaster/e2etests/spring/rpc/examples/numericstring/NumericStringWithSeedEMTest.java

Fix action group

---

core/src/main/kotlin/org/evomaster/core/search/gene/CompositeFixedGene.kt
core/src/main/kotlin/org/evomaster/core/search/gene/uri/UriDataGene.kt
core/src/main/kotlin/org/evomaster/core/search/gene/uri/UrlHttpGene.kt
core/src/main/kotlin/org/evomaster/core/search/impact/impactinfocollection/CompositeFixedGeneImpact.kt
core/src/main/kotlin/org/evomaster/core/search/impact/impactinfocollection/ImpactUtils.kt
core/src/main/kotlin/org/evomaster/core/search/impact/impactinfocollection/value/StringGeneImpact.kt

fix uri problems
add general impact for `CompositeFixedGene`

general CompositeFixedGeneImpact

---

core/src/main/kotlin/org/evomaster/core/problem/external/service/ExternalServiceAction.kt

add `used` and `active` properties

Ex action property

---

core/src/main/kotlin/org/evomaster/core/Main.kt
core/src/main/kotlin/org/evomaster/core/problem/api/service/ApiWsIndividual.kt
core/src/main/kotlin/org/evomaster/core/problem/api/service/ApiWsStructureMutator.kt
core/src/main/kotlin/org/evomaster/core/problem/enterprise/EnterpriseActionGroup.kt
core/src/main/kotlin/org/evomaster/core/problem/enterprise/EnterpriseIndividual.kt
core/src/main/kotlin/org/evomaster/core/problem/external/service/ApiExternalServiceAction.kt
core/src/main/kotlin/org/evomaster/core/problem/external/service/httpws/ExternalService.kt
core/src/main/kotlin/org/evomaster/core/problem/external/service/httpws/ExternalServiceAction.kt
core/src/main/kotlin/org/evomaster/core/problem/external/service/httpws/ExternalServiceHandler.kt
core/src/main/kotlin/org/evomaster/core/problem/external/service/httpws/ExternalServiceInfo.kt
core/src/main/kotlin/org/evomaster/core/problem/external/service/httpws/ExternalServiceRequest.kt
core/src/main/kotlin/org/evomaster/core/problem/external/service/httpws/ExternalServiceUtils.kt
core/src/main/kotlin/org/evomaster/core/problem/external/service/httpws/param/HttpWsResponseParam.kt
core/src/main/kotlin/org/evomaster/core/problem/external/service/param/ResponseParam.kt
core/src/main/kotlin/org/evomaster/core/problem/graphql/GraphQLIndividual.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/RestIndividual.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/resource/RestResourceCalls.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/AbstractRestFitness.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/AbstractRestSampler.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/ResourceRestModule.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/RestModule.kt
core/src/main/kotlin/org/evomaster/core/problem/rpc/RPCIndividual.kt
core/src/main/kotlin/org/evomaster/core/search/Individual.kt
core/src/test/kotlin/org/evomaster/core/problem/external/ExternalServiceUtilsTest.kt
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/wiremock/service/ExternalServiceMockingEMTest.java

add super class `ApiExternalServiceAction`

Api external service

---

core/src/main/kotlin/org/evomaster/core/search/ActionComponent.kt
core/src/main/kotlin/org/evomaster/core/search/Individual.kt
core/src/main/kotlin/org/evomaster/core/search/StructuralElement.kt

add a check for local id setter

Localid invariant

---

core/src/main/kotlin/org/evomaster/core/problem/rest/resource/RestResourceCalls.kt

fix a bug identified with ocvn

fix duplicated reference name

---

core/src/main/kotlin/org/evomaster/core/database/DbAction.kt
core/src/main/kotlin/org/evomaster/core/problem/api/service/ApiWsAction.kt
core/src/main/kotlin/org/evomaster/core/problem/enterprise/EnterpriseActionGroup.kt
core/src/main/kotlin/org/evomaster/core/problem/external/service/ApiExternalServiceAction.kt
core/src/main/kotlin/org/evomaster/core/problem/external/service/httpws/ExternalServiceAction.kt
core/src/main/kotlin/org/evomaster/core/problem/graphql/GraphQLAction.kt
core/src/main/kotlin/org/evomaster/core/problem/httpws/service/HttpWsAction.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/RestCallAction.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/resource/RestResourceCalls.kt
core/src/main/kotlin/org/evomaster/core/problem/rpc/RPCCallAction.kt
core/src/main/kotlin/org/evomaster/core/search/Action.kt
core/src/main/kotlin/org/evomaster/core/search/ActionComponent.kt
core/src/main/kotlin/org/evomaster/core/search/ActionDependentGroup.kt
core/src/main/kotlin/org/evomaster/core/search/ActionTree.kt
core/src/main/kotlin/org/evomaster/core/search/Individual.kt
core/src/main/kotlin/org/evomaster/core/search/StructuralElement.kt
core/src/test/kotlin/org/evomaster/core/search/algorithms/constant/ConstantAction.kt
core/src/test/kotlin/org/evomaster/core/search/algorithms/onemax/OneMaxAction.kt
core/src/test/kotlin/org/evomaster/core/search/gene/binding/BindingAction.kt
core/src/test/kotlin/org/evomaster/core/search/impact/impactinfocollection/individual/IndividualGeneImpactTest.kt
core/src/test/kotlin/org/evomaster/core/search/matchproblem/PrimitiveTypeMatchAction.kt

local id for the structural element has been added.
after the wiremock PR is merged, I will add a check of local id for genes.

local id for structural element

---

core/src/main/kotlin/org/evomaster/core/problem/rest/RestCallAction.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/resource/RestResourceCalls.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/resource/RestResourceNode.kt

fix this problem
```
java.lang.NullPointerException: null
at org.evomaster.core.problem.rest.resource.RestResourceCalls.removeDuplicatedDbActions(RestResourceCalls.kt:344)
```
fix a problem related to `locationId`

fix-scout-api

---

core/src/main/kotlin/org/evomaster/core/search/gene/string/StringGene.kt
core/src/main/kotlin/org/evomaster/core/search/service/mutator/genemutation/ArchiveGeneMutator.kt

fix the problem identified in ind0

check isMutable of specialization gene

---

core/src/main/kotlin/org/evomaster/core/search/EvaluatedIndividual.kt
core/src/main/kotlin/org/evomaster/core/search/Individual.kt
core/src/main/kotlin/org/evomaster/core/search/impact/impactinfocollection/ImpactUtils.kt
core/src/main/kotlin/org/evomaster/core/search/impact/impactinfocollection/ImpactsOfIndividual.kt
core/src/main/kotlin/org/evomaster/core/search/impact/impactinfocollection/MutatedGeneWithContext.kt

Individual index

---

client-java/instrumentation-shared/src/main/java/org/evomaster/client/java/instrumentation/shared/ClassToSchemaUtils.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/object/ClassToSchema.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/object/JsonTaint.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/staticstate/UnitsInfoRecorder.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/object/ClassToSchemaTest.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/object/dtos/CycleDtoA.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/object/dtos/CycleDtoB.java
core/src/main/kotlin/org/evomaster/core/problem/rest/RestActionBuilderV3.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/AbstractRestFitness.kt
core/src/main/kotlin/org/evomaster/core/search/gene/string/StringGene.kt
core/src/main/kotlin/org/evomaster/core/taint/TaintAnalysis.kt
core/src/test/kotlin/org/evomaster/core/problem/rest/RestActionBuilderV3Test.kt
e2e-tests/spring-rest-openapi-v3/src/main/kotlin/com/foo/rest/examples/spring/openapi/v3/wiremock/jsonarray/WmJsonArrayDto.kt
e2e-tests/spring-rest-openapi-v3/src/main/kotlin/com/foo/rest/examples/spring/openapi/v3/wiremock/jsonarray/WmJsonArrayRest.kt
e2e-tests/spring-rest-openapi-v3/src/main/kotlin/com/foo/rest/examples/spring/openapi/v3/wiremock/jsonarray/WmJsonCycleDto.kt
e2e-tests/spring-rest-openapi-v3/src/test/kotlin/org/evomaster/e2etests/spring/openapi/v3/wiremock/jsonarray/WmJsonArrayEMTest.kt

fix StackOverflowError with cycle object

Fix class toschema

---

core/src/main/kotlin/org/evomaster/core/search/gene/collection/ArrayGene.kt
core/src/main/kotlin/org/evomaster/core/search/gene/collection/FixedMapGene.kt

for task https://trello.com/c/KrVbm7RF/863-crash-in-ocvn

reset local id in bindvalue of ArrayGene

---

client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/object/ClassToSchema.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/object/ClassToSchemaTest.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/object/dtos/DtoEnum.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/object/dtos/DtoMap.java
client-java/instrumentation/src/test/java/org/evomaster/client/java/instrumentation/object/dtos/SimpleEnum.java
core/src/test/kotlin/org/evomaster/core/problem/rest/RestActionBuilderV3Test.kt

support dto schema extraction with enum

Classtoschema enum

---

core/src/main/kotlin/org/evomaster/core/output/Clusterer.kt
core/src/main/kotlin/org/evomaster/core/output/TestSuiteSplitter.kt
core/src/main/kotlin/org/evomaster/core/output/service/PartialOracles.kt

Gql split bug

---

client-java/controller/src/main/java/org/evomaster/client/java/controller/ExternalSutController.java

the tests need to be performed on the external controller. since we do not have such support yet, then skip tests for the moment.

Check sut initialized

---

core/src/main/kotlin/org/evomaster/core/EMConfig.kt
core/src/main/kotlin/org/evomaster/core/Main.kt
core/src/main/kotlin/org/evomaster/core/problem/rpc/RPCCallAction.kt
core/src/main/kotlin/org/evomaster/core/search/service/ExecutionInfoReporter.kt
core/src/main/kotlin/org/evomaster/core/search/service/FitnessFunction.kt
core/src/main/kotlin/org/evomaster/core/utils/IncrementalAverage.kt
docs/options.md
e2e-tests/spring-rest-mysql/src/test/kotlin/org/evomaster/e2etests/spring/rest/basic/BasicEMTest.kt
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/testability/TestabilityEMwithAdaptiveMutationTest.java
e2e-tests/spring-rest-openapi-v3/src/test/kotlin/org/evomaster/e2etests/spring/openapi/v3/base/BaseEMTest.kt

record execution info for debugging

Record debug

---

core/src/main/kotlin/org/evomaster/core/problem/externalservice/httpws/service/HarvestActualHttpWsResponseHandler.kt
core/src/test/kotlin/org/evomaster/core/problem/external/service/ExternalHarvesterStrategyTest.kt
core/src/test/kotlin/org/evomaster/core/problem/external/service/HarvestActualHttpWsResponseHandlerTest.kt
core/src/test/kotlin/org/evomaster/core/problem/external/service/MultiHarvestTest.kt

shared client map in order to make a client instance for each thread

Client thread local

---

client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/RPCEndpointsBuilder.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/ObjectParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/Protobuf3ByteStringParam.java
client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/types/Protobuf3ByteStringType.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/grpc/DataTypesTestgRPCEndpointsBuilderTest.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/problem/rpc/grpc/RegistrationServicegRPCEndpointsBuilderTest.java
client-java/controller/src/test/proto/registration_service.proto

support ByteString for proto3 used in gRPC

Grpc registerservice

---

e2e-tests/spring-rpc/spring-rpc-grpc/src/test/java/com/foo/rpc/grpc/examples/spring/GRPCServerController.java

fix grpc controller port with ephemeral ports

fix grpc controller port

---

client-java/instrumentation-shared/src/main/java/org/evomaster/client/java/instrumentation/shared/TaintInputName.java
core/src/main/kotlin/org/evomaster/core/EMConfig.kt
core/src/main/kotlin/org/evomaster/core/Main.kt
core/src/main/kotlin/org/evomaster/core/StaticCounter.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/RestActionBuilderV3.kt
core/src/main/kotlin/org/evomaster/core/search/gene/string/StringGene.kt
docs/options.md
e2e-tests/spring-rest-openapi-v2/pom.xml
e2e-tests/spring-rest-openapi-v2/src/main/java/com/foo/rest/examples/spring/stringminlenght/StringMinLengthApplication.java
e2e-tests/spring-rest-openapi-v2/src/main/java/com/foo/rest/examples/spring/stringminlenght/StringMinLengthRest.java
e2e-tests/spring-rest-openapi-v2/src/main/resources/static/swagger-minlength.json
e2e-tests/spring-rest-openapi-v2/src/test/java/com/foo/rest/examples/spring/stringminlength/StringMinLengthController.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/stringminlength/StringMinLengthEMTest.java

Updating the branch for working on the issue #701.

Created a new branch for working on the issue: #701

---

core/src/main/kotlin/org/evomaster/core/EMConfig.kt
core/src/main/kotlin/org/evomaster/core/Main.kt
core/src/main/kotlin/org/evomaster/core/output/Termination.kt
core/src/main/kotlin/org/evomaster/core/output/TestSuiteSplitter.kt
core/src/main/kotlin/org/evomaster/core/output/service/TestSuiteWriter.kt
core/src/main/kotlin/org/evomaster/core/search/Solution.kt
core/src/main/kotlin/org/evomaster/core/search/service/Archive.kt
core/src/main/kotlin/org/evomaster/core/search/service/Statistics.kt
core/src/main/kotlin/org/evomaster/core/search/service/monitor/SearchProcessMonitor.kt
core/src/test/kotlin/org/evomaster/core/output/service/TestSuiteWriterRPCTest.kt
core/src/test/kotlin/org/evomaster/core/output/service/TestSuiteWriterTest.kt
docs/options.md
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/com/foo/rpc/examples/spring/hypermutation/HypermutationController.java
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/org/evomaster/e2etests/spring/rpc/examples/hypermutation/AdaptiveHypermutationEMTest.java
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/org/evomaster/e2etests/spring/rpc/examples/hypermutation/RPCHypermutationTestBase.java
e2e-tests/spring-rpc/spring-rpc-thrift/src/test/java/org/evomaster/e2etests/spring/rpc/examples/numericstring/NumericStringWithSeedEMTest.java

Save seeded tests

---

README.md
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/Constants.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/visitor/classv/CoverageClassVisitor.java
client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/coverage/visitor/classv/ThirdPartyClassVisitor.java
e2e-tests/e2e-tests-utils/src/test/java/org/evomaster/e2etests/utils/EnterpriseTestBase.java
e2e-tests/spring-graphql/src/test/kotlin/org/evomaster/e2etests/spring/graphql/db/exisitingdata/ExistingDataEMTest.kt
e2e-tests/spring-rest-openapi-v2/src/main/java/com/foo/rest/examples/spring/synthetic/SyntheticApplication.java
e2e-tests/spring-rest-openapi-v2/src/main/java/com/foo/rest/examples/spring/synthetic/SyntheticRest.java
e2e-tests/spring-rest-openapi-v2/src/test/java/com/foo/rest/examples/spring/synthetic/SyntheticController.java
e2e-tests/spring-rest-openapi-v2/src/test/java/org/evomaster/e2etests/spring/examples/synthetic/SyntheticEMTest.java

Security v2 branch

---

core/src/main/kotlin/org/evomaster/core/solver/SMTConditionVisitor.kt
core/src/main/kotlin/org/evomaster/core/solver/SmtLibGenerator.kt
core/src/test/kotlin/org/evomaster/core/solver/SmtLibGeneratorTest.kt

Add support to generate constraints in smtlib from the where of a select query

Solver: add support for constraints from query

---

client-java/controller/src/main/java/org/evomaster/client/java/controller/internal/SutController.java

ExternalController was asking twice for the same List<AdditionalInfo> instance from the instrumented SUT. We are now using the same List<AdditionalInfo> for computing SQL and Mongo heuristics.

duplicate sending of additionalInfoList between agent and controller

---

core/src/main/kotlin/org/evomaster/core/output/auth/CookieWriter.kt
core/src/main/kotlin/org/evomaster/core/output/auth/TokenWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/HttpWsTestCaseWriter.kt
core/src/main/kotlin/org/evomaster/core/output/service/RestTestCaseWriter.kt

This PR adds support for cookie and token handling for when creating python unit tests

Token and Cookie writers

---

core/src/main/kotlin/org/evomaster/core/output/naming/GraphQLActionTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/NamingHelperNumberedTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/NumberedTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/RPCActionTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/RestActionTestCaseNamingStrategy.kt
core/src/main/kotlin/org/evomaster/core/output/naming/TestCaseNamingStrategy.kt
core/src/test/kotlin/org/evomaster/core/output/naming/GraphQLActionNamingStrategyTest.kt
core/src/test/kotlin/org/evomaster/core/output/naming/RestActionNamingStrategyTest.kt
core/src/test/kotlin/org/evomaster/core/output/naming/RestActionTestCaseUtils.kt
core/src/test/kotlin/org/evomaster/core/output/naming/TestCaseDisambiguationTest.kt

For REST individuals, whenever two individuals end in the same path, we go up one path level to add disambiguation.

Path disambiguation

---

e2e-tests/pom.xml
e2e-tests/spring-rest-rsa/pom.xml
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/MySpringBootApplication.java
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/controller/DemoController.java
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/util/CryptoUtil.java
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/util/RSAKeyPairGenerator.java
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/vo/BaseResult.java
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/vo/BindCardReq.java
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/vo/BindCardResp.java
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/vo/CommonReq.java
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/vo/CommonResp.java
e2e-tests/spring-rest-rsa/src/test/java/com/example/demo/controller/DemoControllerTest.java
pom.xml

1. add new module spring-rest-rsa for rsa encryption and signature testing
2. remove the duplicate dependency "com.fasterxml.jackson.core.jackson-databind"

add new module spring-rest-rsa for rsa encryption and signature testing

---

client-java/controller/src/main/java/org/evomaster/client/java/controller/AuthUtils.java
e2e-tests/spring-rest-openapi-v2/src/test/java/com/foo/rest/examples/spring/formlogin/FormLoginController.java

After merging this PR, I will update the EMB SUTs using getForDefaultSpringFormLogin function.

Sending endpoint url as a parameter for auth util

---

core/src/main/kotlin/org/evomaster/core/output/auth/CookieWriter.kt
e2e-tests/spring-rest-bb/src/main/kotlin/com/foo/rest/examples/bb/authcookie/CookieDashboardRest.kt
e2e-tests/spring-rest-bb/src/main/kotlin/com/foo/rest/examples/bb/authcookie/CookieLoginRest.kt
e2e-tests/spring-rest-bb/src/test/kotlin/org/evomaster/e2etests/spring/rest/bb/authcookie/BBAuthCookieRedirectEMTest.kt
e2e-tests/spring-rest-bb/src/test/resources/config/authcookie_redirect.yaml

I changed generated JS test case like this:

Cookie redirection fix

---

client-java/controller/src/main/java/org/evomaster/client/java/controller/internal/SutController.java
client-java/controller/src/test/java/org/evomaster/client/java/controller/internal/db/sql/InitSqlScriptWithSmartDbCleanTest.java

fix the issue in smartdbclean
add test

Fix smartdbclean

---

core-it/src/main/kotlin/bar/examples/it/spring/aiconstraint/numeric/AICMultiTypeApplication.kt
core-it/src/test/kotlin/org/evomaster/core/problem/rest/aiconstraint/numeric/AICMultiTypeCheck.kt
core-it/src/test/kotlin/org/evomaster/core/problem/rest/aiconstraint/numeric/AIGLMCheck.kt
core-it/src/test/kotlin/org/evomaster/core/problem/rest/aiconstraint/numeric/AIGaussianCheck.kt
core/src/main/kotlin/org/evomaster/core/EMConfig.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/classifier/AIModel.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/classifier/GaussianOnlineClassifier.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/classifier/GeneralizedLinearModel.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/classifier/InputEncoderUtils.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/service/AIResponseClassifier.kt
docs/options.md
e2e-tests/spring-rest-rsa/target/maven-archiver/pom.properties

The GLM classifier is added.
The api is also updated so the EvoMaster sampler can generate both valid and invalid samples.

Ai dependency glm gaussian

---

e2e-tests/spring-rest-rsa/pom.xml
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/config/MyBatisConfiguration.java
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/controller/DemoController.java
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/entity/User.java
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/mapper/UserMapper.java
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/service/UserService.java
e2e-tests/spring-rest-rsa/src/main/java/com/example/demo/service/impl/UserServiceImpl.java
e2e-tests/spring-rest-rsa/src/main/resources/application.properties
e2e-tests/spring-rest-rsa/src/main/resources/mapper/UserMapper.xml
e2e-tests/spring-rest-rsa/src/main/resources/schema.sql

In order to test whether evoMaster can insert the data into MySQL DB based on the code analysis, add the SQL operations to the restful API.

Add the SQL opertions to the restful API

---

core-it/src/test/kotlin/org/evomaster/core/problem/rest/aiconstraint/numeric/AIGLMCheck.kt
core-it/src/test/kotlin/org/evomaster/core/problem/rest/aiconstraint/numeric/AIGaussianCheck.kt

The AI models are updated to support probabilistic decision-making policy, as I explained in the following PDF
[AI_Application_in_REST_API_Black_Box_Testing_via_EvoMaster.pdf](https://github.com/WebFuzzing/EAST-papers/blob/master/2025/ai-online-learning/AI_Application_in_REST_API_Black_Box_Testing_via_EvoMaster.pdf)

Desicion making algorithm

---

core-it/src/test/kotlin/org/evomaster/core/problem/rest/aiclassification/AIModelsCheck.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/classifier/AbstractAIModel.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/classifier/GLMModel.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/classifier/GMMModel.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/classifier/GaussianModel.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/classifier/KDEModel.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/classifier/KNNModel.kt
core/src/main/kotlin/org/evomaster/core/problem/rest/classifier/NNModel.kt

Ai moldels integration
